-- | Pentagon numbers
-- Problem 44
-- http://projecteuler.net/problem=44

-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
-- pentagonal numbers are:

-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
-- 70 − 22 = 48, is not pentagonal.

-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
-- difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
-- of D?

import Data.Set (member, fromList)

check :: Int
check = 5000

main :: IO ()
main = do
  putStrLn "Problem 044 - Pentagon numbers"

  putStr "result: "
  print $ minimum
    [ d
    | pk <- pentagonals
    , pj <- takeWhile (< pk) pentagonals
    , let d = pk - pj
    , isPentagonal $ d
    , isPentagonal $ pj + pk
    ]

pentagonal :: Int -> Int
pentagonal n = n * (3 * n - 1) `div` 2

pentagonals :: [Int]
pentagonals = map (pentagonal) [1..check]

isPentagonal :: Int -> Bool
isPentagonal = (`member` fromList pentagonals)
